export const FORM_FIELDS = {
  monday_calories: '',
  tuesday_calories: '',
  wednesday_calories: '',
  thursday_calories: '',
  friday_calories: '',
  saturday_calories: '',
  sunday_calories: '',
  monday_carbohidrates: '',
  tuesday_carbohidrates: '',
  wednesday_carbohidrates: '',
  thursday_carbohidrates: '',
  friday_carbohidrates: '',
  saturday_carbohidrates: '',
  sunday_carbohidrates: '',
  monday_fats: '',
  tuesday_fats: '',
  wednesday_fats: '',
  thursday_fats: '',
  friday_fats: '',
  saturday_fats: '',
  sunday_fats: '',
  monday_protein: '',
  tuesday_protein: '',
  wednesday_protein: '',
  thursday_protein: '',
  friday_protein: '',
  saturday_protein: '',
  sunday_protein: '',
};

export const FORM_TOTAL = {
  totalCalories: '',
  totalCarbohidrates: '',
  totalFats: '',
  totalProtein: '',
};

export const DAYS_FROM_TOTAL = {
  mondayFromTotal: false,
  tuesdayFromTotal: false,
  wednesdayFromTotal: false,
  thursdayFromTotal: false,
  fridayFromTotal: false,
  saturdayFromTotal: false,
  sundayFromTotal: false,
};
